import os
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from config import Config
from utils.logger import setup_logger

logger = setup_logger(__name__)

class RSSGenerator:
    def __init__(self):
        self.rss_file = Config.RSS_FILE
        self.title = Config.RSS_TITLE
        self.description = Config.RSS_DESCRIPTION
        self.link = Config.RSS_LINK
        
        # Ensure RSS directory exists
        os.makedirs(os.path.dirname(self.rss_file), exist_ok=True)
    
    def create_rss_root(self):
        """Create the RSS root element"""
        rss = ET.Element("rss", version="2.0")
        channel = ET.SubElement(rss, "channel")
        
        # Channel elements
        ET.SubElement(channel, "title").text = self.title
        ET.SubElement(channel, "description").text = self.description
        ET.SubElement(channel, "link").text = self.link
        ET.SubElement(channel, "lastBuildDate").text = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S GMT")
        ET.SubElement(channel, "generator").text = "ThreatVision RSS Generator"
        ET.SubElement(channel, "language").text = "zh-CN"
        
        return rss, channel
    
    def get_latest_reports(self, limit=10):
        """Get the latest reports from the data directory"""
        reports = []
        
        if os.path.exists(Config.DATA_DIR):
            # Get all year directories
            years = [d for d in os.listdir(Config.DATA_DIR) if os.path.isdir(os.path.join(Config.DATA_DIR, d))]
            years.sort(reverse=True)  # Sort years from newest to oldest
            
            for year in years:
                year_path = os.path.join(Config.DATA_DIR, year)
                # Get all date directories for this year
                dates = [d for d in os.listdir(year_path) if os.path.isdir(os.path.join(year_path, d))]
                dates.sort(reverse=True)  # Sort dates from newest to oldest
                
                for date in dates:
                    if len(reports) >= limit:
                        break
                    
                    date_path = os.path.join(year_path, date)
                    report_file = os.path.join(date_path, f"Daily_{date}.md")
                    
                    if os.path.exists(report_file):
                        reports.append((date, report_file))
                
                if len(reports) >= limit:
                    break
        
        return reports
    
    def add_item_to_channel(self, channel, date, report_file):
        """Add a report item to the RSS channel"""
        # Parse the report file
        try:
            with open(report_file, "r", encoding="utf-8") as f:
                content = f.read()
            
            # Extract title from the first line
            title = f"安全资讯日报 {date}"
            
            # Create item element
            item = ET.SubElement(channel, "item")
            
            # Item elements
            ET.SubElement(item, "title").text = title
            ET.SubElement(item, "link").text = f"{self.link}/reports/{date}" if self.link else f"/reports/{date}"
            ET.SubElement(item, "description").text = content
            ET.SubElement(item, "pubDate").text = datetime.strptime(date, "%Y-%m-%d").strftime("%a, %d %b %Y %H:%M:%S GMT")
            ET.SubElement(item, "guid", isPermaLink="false").text = date
            
            logger.info(f"Added report {date} to RSS")
            return True
        except Exception as e:
            logger.error(f"Failed to add report {date} to RSS: {e}")
            return False
    
    def generate_rss(self, limit=10):
        """Generate the RSS feed"""
        try:
            logger.info("Generating RSS feed...")
            
            # Create RSS root
            rss, channel = self.create_rss_root()
            
            # Get latest reports
            reports = self.get_latest_reports(limit)
            
            # Add items to channel
            for date, report_file in reports:
                self.add_item_to_channel(channel, date, report_file)
            
            # Create ElementTree
            tree = ET.ElementTree(rss)
            
            # Write to file with proper XML declaration
            with open(self.rss_file, "wb") as f:
                # Write XML declaration
                f.write(b'<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/rss/style.xsl"?><!-- RSS generated by ThreatVision -->\n')
                # Write the XML content
                tree.write(f, encoding="utf-8", xml_declaration=False)
            
            logger.info(f"RSS feed generated successfully: {self.rss_file}")
            return self.rss_file
        except Exception as e:
            logger.error(f"Failed to generate RSS feed: {e}")
            return None
    
    def update_rss(self):
        """Update the RSS feed with the latest reports"""
        return self.generate_rss()
    
    def get_rss_content(self):
        """Get the RSS feed content"""
        try:
            if os.path.exists(self.rss_file):
                with open(self.rss_file, "r", encoding="utf-8") as f:
                    return f.read()
            return None
        except Exception as e:
            logger.error(f"Failed to read RSS file: {e}")
            return None

if __name__ == "__main__":
    # Generate RSS feed
    rss_generator = RSSGenerator()
    rss_generator.generate_rss()
